### ISSUE TITLE
SSO feature

### ISSUE THREAD

**Issue by omkarphadke84** [armakuni/cf-aklogin#2]
Its really nice plugin,but can it be made to use --sso flag from the yml then it would be really great as I could use it for my work 👍 
foo:
  target: api.run.pivotal.io
  username: <username>
  password: <password>
  org: <org>
  space: <space>
  sso:

**Comment by omkarphadke84** [comment]
We use Identity server so ideally when we use --sso we get a URL which I have to open in a browser & then I get one-time code which I enter as password & then I log in to Cloud Foundry.

**Comment by Rob-rls** [comment]
Better late than never I hope...
Latest release enables SSO, but I don't think any of us have used that feature in anger yet. Let us know if it doesn't work.

https://github.com/armakuni/cf-aklogin/releases/tag/v1.3.0

**Comment by omkarphadke84** [comment]
@Rob-rls  thank you very much for adding this feature to this plugin.Now this would help lot of operators/developers around the globe,thanks for your help.
